### PR TITLE
feat: Support discussion event

### LINKED ISSUE #444: proposal: Discussion support
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Discussion support for the GitHub API is in private beta, but from what I understand is this only for people who want to enable the triggering.
The API events and endpoints are most likely already available for actions to use without whitelisting, but confirmation would be needed, which I asked for [here](https://github.com/github/feedback/discussions/4173) (It's also the place to get more info)

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by peaceiris**
Close #444

This feature needs a personal access token as well as #485.

## References

- https://docs.github.com/en/actions/reference/events-that-trigger-workflows#discussion
- https://docs.github.com/en/graphql/guides/using-the-graphql-api-for-discussions
- https://docs.github.com/en/graphql/reference/mutations#adddiscussioncomment
- https://docs.github.com/en/graphql/reference/mutations#updatediscussion
- https://docs.github.com/en/graphql/reference/mutations#locklockable
- https://docs.github.com/en/graphql/reference/mutations#unlocklockable
- https://docs.github.com/en/graphql/reference/mutations#markdiscussioncommentasanswer

## Test this implementation

- Add event `on.discussion`
- Use `70a7e5a7341326e42a96580b0134a4054c47e2a8`

### Workflow

```yaml
name: Label Commenter

on:
  issues:
    types:
      - labeled
      - unlabeled
  pull_request_target:
    types:
      - labeled
      - unlabeled
  discussion:
    types:
      - labeled
      - unlabeled

jobs:
  comment:
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2

      - name: Label Commenter
        uses: peaceiris/actions-label-commenter@70a7e5a7341326e42a96580b0134a4054c47e2a8
        env:
          RUNNER_DEBUG: 1
        with:
          github_token: ${{ secrets.GH_PAT }}
```

### Config

```yaml
labels:
  - name: proposal
    labeled:
      discussion:
        body: Thank you @{{ author }} for suggesting this.

  - name: locked (spam)
    labeled:
      discussion:
        body: |
          This {{ eventName }} \#{{ number }} has been **LOCKED** with the label {{ labelName }}!

          Please do not spam messages on this project. You may get blocked from this repository for doing so.
        locking: lock
        lock_reason: spam
        answer: true

  - name: locked (heated)
    labeled:
      discussion:
        body: |
          This discussion has been **LOCKED** because of heated conversation!

          We appreciate exciting conversations, as long as they won't become too aggressive and/or emotional.
        locking: lock
        lock_reason: too heated
    unlabeled:
      discussion:
        body: |
          This discussion has been unlocked now.
        locking: unlock
```

### CODE REVIEW

**Comment by peaceiris** [comment]
Thank you for the feedback!

About 1: It is difficult to figure it out which comment is the best answer. The latest comment is not always that.

About 2: I have added this to #449.

**Comment by Andre601** [comment]
> About 1: It is difficult to figure it out which comment is the best answer. The latest comment is not always that.

I mean more like:
- You label the discussion
- Bot responds with canned response
- Bot markets own response (The canned response) as answer.

I don't ask for a system that selects the best or most recent one (before the bot) but that the bot would select its own response as answer, if that is doable through the GitHub API.

**Comment by peaceiris** [comment]
`5da68592ce3ed65f0be17ef9eddabe0fa000fc28` supports the following placeholders now.

- author
- labeler
- eventName
- number
- labelName

```yaml
labels:
  - name: proposal
    labeled:
      issue:
        body: &proposal_body Thank you @{{ author }} for suggesting this.
      discussion:
        body: *proposal_body

  - name: locked (spam)
    labeled:
      issue:
        body: &locked_spam_body |
          This {{ eventName }} \#{{ number }} has been **LOCKED** with the label {{ labelName }}!

          Please do not spam messages on this project. You may get blocked from this repository for doing so.
        action: close
        locking: lock
        lock_reason: spam
      pr:
        body: *locked_spam_body
        action: close
        locking: lock
        lock_reason: spam
      discussion:
        body: *locked_spam_body
        locking: lock
        lock_reason: spam
```

**Comment by peaceiris** [comment]
`3dcfc91b6291a15f1d409417f392aeea6db1a4fb` supports `discussion.answer: true` now.

**Comment by peaceiris** [comment]
`439d9ad8e37a55809451cd7a938fe2b6bd9dc29e` fixes `{{ eventName }}` as follows:

- if `on.issues`, returns `issue`
- if `on.(pull_request|pull_request_target)`, returns `pull request`
- if `on.discussion`, returns `discussion`

**Comment by peaceiris** [comment]
This feature works without a personal access token now, but #485 still requires that.

```yaml
name: Label Commenter

on:
  issues:
    types:
      - labeled
      - unlabeled
  pull_request_target:
    types:
      - labeled
      - unlabeled
  discussion:
    types:
      - labeled
      - unlabeled

permissions:
  contents: read
  issues: write
  pull-requests: write
  discussions: write

jobs:
  comment:
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    steps:
      - name: Label Commenter
        uses: peaceiris/actions-label-commenter@c2d00660c86f2b9ed0fb35b372c451558eba85b3
```

**Pull request merged**
