### PR TITLE
feat: Toggle pull-request draft status

### LINKED ISSUE #436: proposal: Add action to turn PR into Draft and vice-versa
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
There should be additional actions to turn a PR into a Draft or turn a Draft into a PR.
Perhaps the `open` action could be re-used here to do draft -> PR?

**Describe alternatives you've considered**
Doing it manually... obviously.

**Additional context**
We have a specific setup for PRs in a repository, where a PR is a draft until it's ready for review and merge in which case it will receive a `Status: Ready` label, where the comment action comments about this change.
Having a way to directly change the PRs draft-status on (un)label would allow us to remove one extra step (Lazyness for the win!)

### PR DESCRIPTION
**Pull request by peaceiris**
Close #436

## Overview

My proposal about a REST API to toggle pull-request draft status ([pulls.update: Change pull-request draft status · Issue #69 · octokit/rest.js](https://github.com/octokit/rest.js/issues/69)) has been rejected since the GitHub API v4 (GraphQL API) has the ability to do that.

Unfortunately, an auto-generated access token called `GITHUB_TOKEN` seems not to have full control permission of the GraphQL API. We got the error `Resource not accessible by integration` with the GitHub API v4 and `GITHUB_TOKEN`. This problem may be related to the following thread.

- [API v4 - Unable to Retrieve Email - Resource not accessible by integration - GitHub Ecosystem - GitHub Support Community](https://github.community/t/api-v4-unable-to-retrieve-email-resource-not-accessible-by-integration/13831/3)

This pull-request uses a personal access token with a `public_repo` scope (for a public repository) as a workaround.

## References

- [convertPullRequestToDraft - Mutations - GitHub Docs](https://docs.github.com/en/graphql/reference/mutations#convertpullrequesttodraft)
- [markPullRequestReadyForReview - Mutations - GitHub Docs](https://docs.github.com/en/graphql/reference/mutations#markpullrequestreadyforreview)
- https://github.com/actions/toolkit/blob/%40actions/tool-cache%401.1.1/packages/github/README.md?plain=1#L32
	- [octokit/graphql.js: GitHub GraphQL API client for browsers and Node](https://github.com/octokit/graphql.js)
	- [octokit/graphql-schema: GitHub’s GraphQL Schema with validation. Automatically updated.](https://github.com/octokit/graphql-schema)

### Workflow

Provide a personal access token with a `public_repo` scope (for a public repository) as the `GH_PAT` secret.

```yaml
name: Label Commenter

on:
  issues:
    types:
      - labeled
      - unlabeled
  pull_request_target:
    types:
      - labeled
      - unlabeled

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2

      - name: Label Commenter
        uses: peaceiris/actions-label-commenter@06a7f624808ccde484c21bf2bc8fdbdf71a19339
        env:
          RUNNER_DEBUG: 1
        with:
          github_token: ${{ secrets.GH_PAT }}
```

### Label Commenter Config

Add `draft: true` or `draft: false` to a `pr` field.

```yaml
labels:
  - name: invalid
    labeled:
      pr:
        body: Thank you @{{ pull_request.user.login }} for suggesting this. Please follow the pull request templates.
        action: close
        draft: true

  - name: locked (heated)
    labeled:
      pr:
        body: |
          This pull-request has been **LOCKED** because of heated conversation!

          We appreciate exciting conversations, as long as they won't become too aggressive and/or emotional.
        locking: lock
        lock_reason: too heated
        draft: true
    unlabeled:
      pr:
        body: |
          This pull-request has been unlocked now.
        locking: unlock
        draft: false
```

### CODE REVIEW

**Comment by Andre601** [comment]
Got errors:
https://github.com/Readme-Workflows/recent-activity/pull/94/checks?check_run_id=3279903747

Current workflow file:
https://github.com/Readme-Workflows/recent-activity/blob/97a64b0dded82b0a130a249d24f3ee0980c8062c/.github/workflows/pr_comment.yml
(LABEL_COMMENTER is a PAT with public_repo scope)

Current label commenter file:
https://github.com/Readme-Workflows/recent-activity/blob/97a64b0dded82b0a130a249d24f3ee0980c8062c/.github/label-commenter-config.yml

Test PR:
https://github.com/Readme-Workflows/recent-activity/pull/94

**Comment by peaceiris** [comment]
Thank you for the super quick try! Please use `06a7f624808ccde484c21bf2bc8fdbdf71a19339`.

**Comment by Andre601** [comment]
It seems to work, but the downside is, that the user account of the PAT is used for the comment:
image

**Comment by peaceiris** [comment]
Yes. I totally agree with you. We have no way to avoid that behavior with a pat.

I think `GITHUB_TOKEN` is better than a personal access token. So, I am going to post a suggestion about permission improvement about `GITHUB_TOKEN` with GraphQL API to GitHub Community later.

**Comment by Andre601** [comment]
> Yes. I totally agree with you. We have no way to avoid that behavior with a pat.
> 
> I think `GITHUB_TOKEN` is better than a personal access token. So, I am going to post a suggestion about permission improvement about `GITHUB_TOKEN` with GraphQL API to GitHub Community later.

https://github.community/t/allow-the-github-token-to-also-have-rights-for-converting-prs-to-draft-or-vice-versa/194555

You're welcome. (Comment with anything I missed to mention or explain)

**Comment by Andre601** [comment]
I for now have a dedicated account for the Repository where I want to use the draft feature and it seems to work fine.
image

**Comment by peaceiris** [comment]
Good!

**Comment by peaceiris** [comment]
This will be merged and released as the v1.11.0 with other new features. Watch [v1.11.0 Milestone](https://github.com/peaceiris/actions-label-commenter/milestone/1). We can continue to use `06a7f624808ccde484c21bf2bc8fdbdf71a19339` until the v1.11.0 will be published.

**Pull request merged**
